---
title: "Regression"
output: html_document
date: "2022-09-22"
---

## Package

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readxl)
library(dplyr)
library(patchwork)
library(tidyverse)
library(reshape2)
library(ggrepel)
library(MASS)
library(glmnet)
library(spdep)
library(lme4)
library(MuMIn)
library(car)
library(graphics)
library(bcmixed)
library(sf)
library(FNN)
```

# IA and study region load

```{r input excel}
data_all = read.csv("Data_all.csv")

df = data.frame(assisstance_rate_type1 = data_all$assisstance_rate_type1, assisstance_rate_type2 = data_all$assisstance_rate_type2, population = data_all$population, wind_50_up = data_all$wind_50_up, hwm = data_all$hwm, SVI = data_all$SVI, node1 = data_all$node1, event_name = data_all$event_name, SS_scale = data_all$SS_scale,SS_scale2 = data_all$SS_scale2, longtitude = data_all$longitude, latitude = data_all$latitude)

```


```{r}
df$assisstance_rate_type1 = exp(df$assisstance_rate_type1) / (1 + exp(df$assisstance_rate_type1))
df$assisstance_rate_type2 = exp(df$assisstance_rate_type2) / (1 + exp(df$assisstance_rate_type2))

df$assisstance_rate_type1_scale = scale(df$assisstance_rate_type1) 
df$assisstance_rate_type1_scale = df$assisstance_rate_type1_scale - min(df$assisstance_rate_type1_scale) + 1e-09

df$assisstance_rate_type2_scale = scale(df$assisstance_rate_type2) 
df$assisstance_rate_type2_scale = df$assisstance_rate_type2_scale - min(df$assisstance_rate_type2_scale) + 1e-09

df$node1_scale = scale(df$node1) 
df$node1_scale = df$node1_scale - min(df$node1_scale) + 1e-09

df$SVI_scale = scale(df$SVI) 
df$SVI_scale = df$SVI_scale - min(df$SVI_scale) + 1e-09

df$population_scale = scale(df$population) 
df$population_scale = df$population_scale - min(df$population_scale) + 1e-09

df$hwm_scale = scale(df$hwm) 
df$hwm_scale = df$hwm_scale - min(df$hwm_scale) + 1e-09

df$wind_50_up_scale = scale(df$wind_50_up) 
df$wind_50_up_scale = df$wind_50_up_scale - min(df$wind_50_up_scale) + 1e-09

lm_model <- lm(assisstance_rate_type1_scale ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
bc <- boxcox(assisstance_rate_type1_scale ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
bc$x[which(bc$y == max(bc$y))]
summary(lm_model)
plot(lm_model)

lm_model <- lm(assisstance_rate_type1_scale^(0.1818182) ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
summary(lm_model)
plot(lm_model)

lm_model_2 <- lm(assisstance_rate_type2_scale ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
bc <- boxcox(assisstance_rate_type2_scale ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
bc$x[which(bc$y == max(bc$y))]
summary(lm_model_2)
plot(lm_model_2)

lm_model_2 <- lm(assisstance_rate_type1_scale^(0.1414141) ~ node1_scale + SVI_scale + population_scale + hwm_scale + wind_50_up_scale, data = df)
summary(lm_model_2)
plot(lm_model_2)
```

```{r}
selected_model <- step(lm_model, direction = "both")
summary(selected_model)
```









